source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'ReactiveArray_Tests' do
  pod 'ReactiveArray', :path => '../'

  pod 'ReactiveCocoa', '~> 4.1.0'
  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '~> 3.2.0'
end
